backend:
  listen:
    host: 127.0.0.1

  database:
    connection:
      host: 127.0.0.1

  logger:
    meta:
      env: prod
    level: warn
    overrides:
      - matchers:
          plugin: scaffolder
        level: debug
      - matchers:
          plugin: mca
        level: info
      - matchers:
          plugin: api-platform
        level: debug
      - matchers:
          plugin: analytics
        level: debug
      #- matchers:
      #    plugin: search
      # level: debug

auth:
  autologout:
    enabled: true
    idleTimeoutMinutes: 10
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
      userEntityRef: user:default/guest
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail

catalog:
  locations:
    - type: file
      target: ../../examples/templates/sb-init/template.yaml
    - type: file
      target: ../../examples/templates/template/template.yaml
