backend:
  listen:
    host: 0.0.0.0

  cors:
    origin: http://localhost:7007

  database:
    connection:
      host: postgres-db

auth:
  autologout:
    enabled: true
    idleTimeoutMinutes: 10
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
      userEntityRef: user:default/guest
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail