apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.k8s.yaml: |
    app:
      baseUrl: http://localhost

    backend:
      baseUrl: http://localhost
      listen:
        port: 7007
      cors:
        origin: http://localhost
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}

    auth:
      autologout:
        enabled: true
        idleTimeoutMinutes: 10
      environment: prod
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
          userEntityRef: user:default/guest
        microsoft:
          prod:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            domainHint: ${AZURE_TENANT_ID}
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
    catalog:
      rules:
        - allow:
            [
              Component,
              System,
              API,
              Resource,
              Template,
              Domain,
              Location,
              Group,
              User,
            ]
      providers:
        microsoftGraphOrg:
          default:
            schedule:
              frequency: { minutes: 30 }
              timeout: { minutes: 5 }
              initialDelay: { minutes: 1 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: carth-backstage:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: POSTGRES_HOST
              value: postgres.backstage
            - name: POSTGRES_PORT
              value: '5432'
            - name: NODE_OPTIONS
              value: '--trace-warnings'
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
          volumeMounts:
            - name: app-config
              mountPath: /app/app-config.k8s.yaml
              subPath: app-config.k8s.yaml
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: backstage-config
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http