apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: team-a
  name: ext-generated-component
  title: Ext Generated Documents
  description: Documentation generated externally
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: PRD
  owner: group:default/team-a.o