export const ANNOTATION_API_NAME = "api-name";
export const ANNOTATION_API_PROJECT = "api-project";
export const ANNOTATION_API_VERSION = "api-version";

export const ANNOTATION_IMAGE_VERSION = "image-version";
export const ANNOTATION_SERVICE_NAME = "service-name";
export const ANNOTATION_SERVICE_PROJECT = "service-project";
export const ANNOTATION_SERVICE_VERSION = "service-version";
export const ANNOTATION_SERVICE_PLATFORM = "service-platform";

export const CATALOG_METADATA = "metadata";
export const CATALOG_METADATA_NAME = `${CATALOG_METADATA}.name`;
export const CATALOG_METADATA_NAMESPACE = `${CATALOG_METADATA}.namespace`;
export const CATALOG_METADATA_DESCRIPTION = `${CATALOG_METADATA}.description`;

export const CATALOG_METADATA_API_NAME = `${CATALOG_METADATA}.${ANNOTATION_API_NAME}`;
export const CATALOG_METADATA_API_VERSION = `${CATALOG_METADATA}.${ANNOTATION_API_VERSION}`;
export const CATALOG_METADATA_IMAGE_VERSION = `${CATALOG_METADATA}.${ANNOTATION_IMAGE_VERSION}`;
export const CATALOG_METADATA_SERVICE_NAME = `${CATALOG_METADATA}.${ANNOTATION_SERVICE_NAME}`;
export const CATALOG_METADATA_SERVICE_VERSION = `${CATALOG_METADATA}.${ANNOTATION_SERVICE_VERSION}`;
export const CATALOG_METADATA_SERVICE_PLATFORM = `${CATALOG_METADATA}.${ANNOTATION_SERVICE_PLATFORM}`;

export const CATALOG_SPEC_LIFECYCLE = "spec.lifecycle";
export const CATALOG_SPEC_TYPE = "spec.type";
export const CATALOG_RELATIONS = "relations";
export const CATALOG_KIND = "kind";

