apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-local
  description: Local petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: ./petstore.oas.yaml