apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: depo-test-template
  title: Test repo init
  description: Create a test API repository 7
spec:
  owner: group:default/prd.10.gemz.depo.ado.o
  type: repository
 
  parameters:
    - title: "General Information"
      properties:
        dryRun:
          title: "Dry Run"
          type: boolean
          default: false
          description: "Enable dry run mode"
        project:
          title: "DEFL code"
          description: What is the DEFL code for the project?
          type: string
          default: "java-playground"      
        volume_type:
          title: Volume Type
          type: string
          description: The volume type to be used
          default: gp2
          enum:
            - gp2
            - gp3
            - io1
            - io2
            - sc1
            - st1
            - standard
        app_code:
          title: "Application Code"
          description: What is the application code for the repository to create?
          type: string
          ui:field: ProjectPicker
        repo_name:
          title: "Repository Name"
          description: What is the name of the repository to create?
          type: string
      required:
        - dryRun
        - project
        - app_code
        - volume_type
        - repo_name
      ui:order:
        - dryRun
        - project
        - app_code
        - volume_type
        - repo_name
    - title: "Repository Location"
      dependencies:
        - project
        - repo_name
      properties:
        repo_url:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com  
            allowedOrganizations:
              - thierrycarels0265
            allowedProjects:
              - ${{ parameters.project }}
            allowedRepos:
              - ${{ parameters.repo_name }}
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                azure: []
        repo_branch:
          title: Repository Branch readonly set to main
          type: string
          default: main
          ui:field: RepoBranchPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                azure: []
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          project: ${{ parameters.project }}
          repo_name: ${{ parameters.repo_name }}
          repo_url: ${{ parameters.repo_url }}
 
    - action: debug:log
      id: write-all-workspace-directory
      name: List the workspace directory with file contents
      input:
        listWorkspace: with-contents
 
    - action: debug:log
      id: write-workspace-directory
      name: List the workspace directory
      input:
        listWorkspace: true
 
    - id: publish
      name: Publish
      action: publish:azure
      if: ${{ parameters.dryRun !== true }}
      input:
        repoUrl: "dev.azure.com?organization=thierrycarels0265&project=${{ parameters.project }}&repo=${{ parameters.repo_name }}"
        defaultBranch: main
        gitCommitMessage: 'Scaffolded by ${{ user.entity.spec.profile.email }}'
        gitAuthorName: 'Backstage'
        gitAuthorEmail: ''
        token: ${{ secrets.USER_OAUTH_TOKEN }}
 
  output:
    text:
      - title: Summary
        content: |
          ## Completed
          - Created repo ${{ parameters.repo_name }} at ${{ steps['publish'].output.remoteUrl }}
 
          ## Next steps
          - Configure your local development environment